spring.application.name=Stock1337

spring.datasource.url=jdbc:mysql://localhost:3306/stock1337db
#spring.datasource.url=jdbc:mysql://mysqldb:3306/IT_Support?createDatabaseIfNotExist=true&createIfNotExists=true
#spring.jpa.database=MYSQL
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.username=root
spring.datasource.password=${DB_PASSWORD}
spring.jpa.properties.hibernate.dialect = org.hibernate.dialect.MySQL8Dialect

application.security.jwt.secret-key=357638792F423F4428472B4B6250655368566D597133743677397A2443264629
application.security.jwt.expiration=86400000

server.port=8087
